
package ch.hcisolutions.index;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "downloadHttpPost", targetNamespace = "http://www.hcisolutions.ch/index")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DownloadHttpPost {


    /**
     * 
     * @param system
     * @param catalogOwnerGln
     * @param id
     * @param lang
     * @param fromdate
     */
    @WebMethod(operationName = "DownloadCatalog")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void downloadCatalog(
        @WebParam(name = "id", partName = "id")
        String id,
        @WebParam(name = "lang", partName = "lang")
        String lang,
        @WebParam(name = "fromdate", partName = "fromdate")
        String fromdate,
        @WebParam(name = "system", partName = "system")
        String system,
        @WebParam(name = "catalogOwnerGln", partName = "catalogOwnerGln")
        String catalogOwnerGln);

}
