
package ch.hcisolutions.index;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "download", targetNamespace = "http://www.hcisolutions.ch/index", wsdlLocation = "file:/home/thomas/artikelstamm/git/ch.hcisolutions.index/rsc/hcisolutions_index_download.wsdl")
public class Download
    extends Service
{

    private final static URL DOWNLOAD_WSDL_LOCATION;
    private final static WebServiceException DOWNLOAD_EXCEPTION;
    private final static QName DOWNLOAD_QNAME = new QName("http://www.hcisolutions.ch/index", "download");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/thomas/artikelstamm/git/ch.hcisolutions.index/rsc/hcisolutions_index_download.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOWNLOAD_WSDL_LOCATION = url;
        DOWNLOAD_EXCEPTION = e;
    }

    public Download() {
        super(__getWsdlLocation(), DOWNLOAD_QNAME);
    }

    public Download(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOWNLOAD_QNAME, features);
    }

    public Download(URL wsdlLocation) {
        super(wsdlLocation, DOWNLOAD_QNAME);
    }

    public Download(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOWNLOAD_QNAME, features);
    }

    public Download(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Download(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DownloadSoap
     */
    @WebEndpoint(name = "downloadSoap")
    public DownloadSoap getDownloadSoap() {
        return super.getPort(new QName("http://www.hcisolutions.ch/index", "downloadSoap"), DownloadSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DownloadSoap
     */
    @WebEndpoint(name = "downloadSoap")
    public DownloadSoap getDownloadSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hcisolutions.ch/index", "downloadSoap"), DownloadSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns DownloadSoap
     */
    @WebEndpoint(name = "downloadSoap12")
    public DownloadSoap getDownloadSoap12() {
        return super.getPort(new QName("http://www.hcisolutions.ch/index", "downloadSoap12"), DownloadSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DownloadSoap
     */
    @WebEndpoint(name = "downloadSoap12")
    public DownloadSoap getDownloadSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hcisolutions.ch/index", "downloadSoap12"), DownloadSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOWNLOAD_EXCEPTION!= null) {
            throw DOWNLOAD_EXCEPTION;
        }
        return DOWNLOAD_WSDL_LOCATION;
    }

}
